#!/data/data/com.termux/files/usr/bin/bash
#
# Pixel bridge bootstrap for Termux.
#
# Safe defaults:
#   * no Tailscale auth key is created or stored here;
#   * the health stub binds to localhost;
#   * no model, APK, or native binary is downloaded;
#   * rerunning this file preserves the SFTP key and a running MCP process.
#
# Optional environment:
#   MCP_COMMAND='python ~/bin/my_mcp_server.py --port 8081'
#   MCP_BIND_ADDRESS=0.0.0.0   # only when a Tailscale-reachable listener is wanted
#   MCP_PORT=8081
#   INSTALL_LLAMA_CPP=1        # source checkout + local build, still no model
#   LLAMA_SRC_DIR=$HOME/src/llama.cpp
#   SFTP_KEY_SLOT=$HOME/.config/pixel-bridge/ssh/id_ed25519
#
# The default process is only a liveness stub. Replace it with MCP_COMMAND
# after the real server has been tested on-device.

set -Eeuo pipefail

BRIDGE_DIR="${BRIDGE_DIR:-${HOME}/.config/pixel-bridge}"
SSH_DIR="${BRIDGE_DIR}/ssh"
SFTP_KEY_SLOT="${SFTP_KEY_SLOT:-${SSH_DIR}/id_ed25519}"
MCP_BIND_ADDRESS="${MCP_BIND_ADDRESS:-127.0.0.1}"
MCP_PORT="${MCP_PORT:-8081}"
HEALTH_HOST="${HEALTH_HOST:-127.0.0.1}"
HEALTH_URL="${HEALTH_URL:-http://${HEALTH_HOST}:${MCP_PORT}/health}"
PID_FILE="${BRIDGE_DIR}/mcp.pid"
LOG_FILE="${BRIDGE_DIR}/mcp.log"
HEALTH_STUB="${BRIDGE_DIR}/mcp_health_stub.py"
LLAMA_SRC_DIR="${LLAMA_SRC_DIR:-${HOME}/src/llama.cpp}"
LLAMA_BUILD_DIR="${LLAMA_BUILD_DIR:-${LLAMA_SRC_DIR}/build}"
LLAMA_REPO_URL="${LLAMA_REPO_URL:-https://github.com/ggerganov/llama.cpp.git}"

log() {
  printf '[pixel-bridge] %s\n' "$*"
}

die() {
  printf '[pixel-bridge] ERROR: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

install_termux_packages() {
  require_cmd pkg
  log "Updating Termux package indexes"
  pkg update -y

  # Keep the base install small: these are control-plane tools, not an ML
  # runtime. cmake/make/clang are added only for the optional source build.
  local packages=(curl git openssh python)
  if [[ "${INSTALL_LLAMA_CPP:-0}" == "1" ]]; then
    packages+=(clang cmake make)
  fi
  log "Installing: ${packages[*]}"
  pkg install -y "${packages[@]}"
}

write_health_stub() {
  mkdir -p "$BRIDGE_DIR"
  if [[ -e "$HEALTH_STUB" ]]; then
    return
  fi

  cat >"$HEALTH_STUB" <<'PYTHON'
#!/usr/bin/env python3
"""Small offline liveness endpoint; this is not an MCP protocol server."""
import json
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path != "/health":
            self.send_error(404, "use /health")
            return
        body = json.dumps(
            {"status": "ok", "service": "pixel-mcp-health-stub"}
        ).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, format_string, *args):
        return


def main():
    address = sys.argv[1] if len(sys.argv) > 1 else "127.0.0.1"
    port = int(sys.argv[2]) if len(sys.argv) > 2 else 8081
    ThreadingHTTPServer((address, port), HealthHandler).serve_forever()


if __name__ == "__main__":
    main()
PYTHON
  chmod 700 "$HEALTH_STUB"
}

ensure_sftp_key() {
  mkdir -p "$SSH_DIR"
  chmod 700 "$SSH_DIR"

  if [[ ! -e "$SFTP_KEY_SLOT" ]]; then
    require_cmd ssh-keygen
    log "Creating an Ed25519 SFTP key in the local key slot"
    ssh-keygen -q -t ed25519 -N "" -f "$SFTP_KEY_SLOT" \
      -C "pixel-bridge@${HOSTNAME:-pixel-android}"
  elif [[ ! -e "${SFTP_KEY_SLOT}.pub" ]]; then
    require_cmd ssh-keygen
    log "Recreating the missing public half of the existing SFTP key"
    ssh-keygen -y -f "$SFTP_KEY_SLOT" >"${SFTP_KEY_SLOT}.pub"
  fi

  chmod 600 "$SFTP_KEY_SLOT"
  chmod 644 "${SFTP_KEY_SLOT}.pub"
  log "SFTP public key slot: ${SFTP_KEY_SLOT}.pub"
  log "Install that public key on the intended Vultr account; never commit the private key."
}

show_tailscale_status() {
  if command -v tailscale >/dev/null 2>&1; then
    log "Tailscale CLI found; showing status without changing auth or routes"
    tailscale status || log "Tailscale status is unavailable; check the Android app"
  else
    log "Tailscale CLI is not installed in Termux."
    log "Use the official Android Tailscale app, approve its VPN, sign in, and name this device pixel-8a."
    log "No Tailscale auth key is generated by this script."
  fi
}

start_mcp() {
  if [[ "${SKIP_MCP:-0}" == "1" ]]; then
    log "SKIP_MCP=1; leaving the MCP listener unchanged"
    return
  fi

  mkdir -p "$BRIDGE_DIR"
  if [[ -s "$PID_FILE" ]]; then
    local old_pid
    old_pid="$(cat "$PID_FILE")"
    if [[ "$old_pid" =~ ^[0-9]+$ ]] && kill -0 "$old_pid" 2>/dev/null; then
      log "MCP process already running with PID ${old_pid}"
      return
    fi
    rm -f "$PID_FILE"
  fi

  local pid
  if [[ -n "${MCP_COMMAND:-}" ]]; then
    log "Starting configured MCP command on port ${MCP_PORT}"
    nohup sh -c "$MCP_COMMAND" >>"$LOG_FILE" 2>&1 &
    pid=$!
  else
    write_health_stub
    log "Starting the offline /health stub on ${MCP_BIND_ADDRESS}:${MCP_PORT}"
    nohup python "$HEALTH_STUB" "$MCP_BIND_ADDRESS" "$MCP_PORT" \
      >>"$LOG_FILE" 2>&1 &
    pid=$!
  fi
  printf '%s\n' "$pid" >"$PID_FILE"
  chmod 600 "$PID_FILE" "$LOG_FILE" 2>/dev/null || true

  local attempt
  for attempt in 1 2 3 4 5 6 7 8 9 10; do
    if curl --fail --silent --show-error --max-time 2 "$HEALTH_URL" >/dev/null; then
      log "Health check passed: ${HEALTH_URL}"
      return
    fi
    sleep 1
  done
  log "Health check failed; inspect ${LOG_FILE}"
  return 1
}

install_llama_cpp_from_source() {
  if [[ "${INSTALL_LLAMA_CPP:-0}" != "1" ]]; then
    return 0
  fi
  require_cmd git
  require_cmd cmake

  mkdir -p "$(dirname "$LLAMA_SRC_DIR")"
  if [[ ! -d "${LLAMA_SRC_DIR}/.git" ]]; then
    log "Cloning llama.cpp source; no executable or model is committed"
    git clone --depth 1 "$LLAMA_REPO_URL" "$LLAMA_SRC_DIR"
  else
    log "llama.cpp source already exists at ${LLAMA_SRC_DIR}; leaving it unchanged"
  fi

  cmake -S "$LLAMA_SRC_DIR" -B "$LLAMA_BUILD_DIR" \
    -DGGML_OPENMP=ON -DCMAKE_BUILD_TYPE=Release
  cmake --build "$LLAMA_BUILD_DIR" --target llama-server \
    --parallel "${LLAMA_JOBS:-2}"
  log "Source build complete. Download a permitted GGUF at runtime; do not put it in git."
}

main() {
  install_termux_packages
  require_cmd curl
  require_cmd python
  ensure_sftp_key
  show_tailscale_status
  install_llama_cpp_from_source
  start_mcp
  log "Done. Default listener is local-only; set MCP_BIND_ADDRESS=0.0.0.0 deliberately for mesh access."
}

main "$@"
