#!/usr/bin/env python3
"""Generate a deterministic index of acceptance-criteria-like IDs.

The script intentionally uses only the Python standard library so it can run
offline in a checkout with no project dependencies installed.
"""

from __future__ import annotations

import argparse
import os
import re
import tempfile
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote


# Supported examples include AC-001, AC-12-login, AC_001, and AC123.
# Requiring a separator or a digit after "AC" avoids matching words such as
# "ACCEPTANCE".
AC_ID_RE = re.compile(
    r"(?<![A-Za-z0-9])AC(?:[0-9][A-Za-z0-9._-]*|[-_][A-Za-z0-9]+(?:[-_.][A-Za-z0-9]+)*)\b"
)


@dataclass(frozen=True)
class Occurrence:
    path: Path
    line: int


def find_ac_ids(source_dir: Path, output_path: Path) -> dict[str, list[Occurrence]]:
    """Return AC-like IDs and their source locations under *source_dir*."""
    occurrences: dict[str, list[Occurrence]] = defaultdict(list)
    if not source_dir.is_dir():
        return occurrences

    output_path = output_path.resolve()
    for path in sorted(source_dir.rglob("*")):
        if not path.is_file() or path.resolve() == output_path:
            continue

        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            # OpenSpec is documentation, but ignoring an unreadable or
            # non-text entry makes the offline indexer safe for mixed trees.
            continue

        relative_path = path.relative_to(source_dir)
        for line_number, line in enumerate(text.splitlines(), start=1):
            for match in AC_ID_RE.finditer(line):
                occurrences[match.group(0)].append(
                    Occurrence(relative_path, line_number)
                )

    return occurrences


def render_index(occurrences: dict[str, list[Occurrence]], source_label: str) -> str:
    """Render the index as stable Markdown."""
    lines = [
        "# AC ID Index",
        "",
        "Generated by `scripts/gen_ac_id_index.py` from "
        f"`{source_label}`. Do not edit manually.",
        "",
    ]

    if not occurrences:
        lines.append("No AC-like IDs found.")
        lines.append("")
        return "\n".join(lines)

    lines.extend(
        [
            "| AC ID | Source locations |",
            "| --- | --- |",
        ]
    )
    for ac_id in sorted(occurrences):
        locations = []
        for occurrence in sorted(
            occurrences[ac_id], key=lambda item: (item.path.as_posix(), item.line)
        ):
            relative = quote(occurrence.path.as_posix(), safe="/._-")
            locations.append(
                f"[{occurrence.path.as_posix()}:{occurrence.line}]"
                f"({relative}#L{occurrence.line})"
            )
        lines.append(f"| `{ac_id}` | {', '.join(locations)} |")

    lines.append("")
    return "\n".join(lines)


def write_atomically(path: Path, content: str) -> None:
    """Write *content* to *path* without leaving a partial output file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: str | None = None
    try:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
        )
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as file:
            file.write(content)
        os.replace(temporary_name, path)
        temporary_name = None
    finally:
        if temporary_name is not None:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass


def parse_args() -> argparse.Namespace:
    repository_root = Path(__file__).resolve().parents[1]
    default_source = repository_root / "docs" / "openspec"
    parser = argparse.ArgumentParser(
        description="Index AC-like IDs in docs/openspec for offline lookup."
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=default_source,
        help=f"directory to scan (default: {default_source})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=default_source / "AC_INDEX.md",
        help=f"Markdown index path (default: {default_source / 'AC_INDEX.md'})",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repository_root = Path(__file__).resolve().parents[1]
    default_source = repository_root / "docs" / "openspec"
    source_dir = args.source_dir.resolve()
    output_path = args.output.resolve()
    occurrences = find_ac_ids(source_dir, output_path)
    source_label = (
        "docs/openspec"
        if source_dir == default_source.resolve()
        else args.source_dir.as_posix()
    )
    write_atomically(output_path, render_index(occurrences, source_label))
    print(f"Wrote {output_path} ({len(occurrences)} AC-like IDs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
